/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://x54lwgff2bbe7nws2yrxhx3xzy.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-cmhjvaeyxjbbjjqr2rs5354flq",
    "aws_cognito_identity_pool_id": "eu-central-1:85dfe8b9-bdf7-4acc-9b2f-493309a64e58",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_WPjaTgO75",
    "aws_user_pools_web_client_id": "5qbas7ue723n7ui3aemk8glbbt",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "cookbook-storage-57b1db2a135139-staging",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
